
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Latest</title>
                 <style>
                  #load_date{color:green}
                   #code_snippet{color:black}
                 </style>
                  <link rel="stylesheet"
                                         href="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.2.1/build/styles/default.min.css">
                                  <script src="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.2.1/build/highlight.min.js"></script>
                                  <script>hljs.initHighlightingOnLoad();</script>
                  </head>
                  <body>
                <table>
                <#list codes as code>
                <tr>
                <td>
                 <span id="load_date">${code.date}</span>
                 <pre id="code_snippet"><code>${code.code}</code></pre>
                </td>
                </tr>
                </#list>
                </table>
</body>
</html>


